import Head from "next/head";

import { getMonth } from "../components/months";
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google calendar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </div>
  );
}
